use std::collections::HashMap;
use std::path::Path;

use crate::error::ParseError;
use crate::ir::{CodegenMeta, JobIr};

/// Entry point: generate DAG .py files for all eligible IR entries.
///
/// For each eligible job, looks for an optional override config at:
///   `<config_dir>/<env>/<job_id>.json`
/// If found, its key→value pairs override the IR-derived substitution defaults.
/// Only keys present in the config are overridden; everything else falls back to IR values.
///
/// Returns the number of DAG files successfully written.
pub fn generate_dags(
    irs: &[JobIr],
    output_dir: &Path,
    templates_dir: &Path,
    config_dir: &Path,
    company: &str,
    env: &str,
) -> Result<usize, ParseError> {
    let dags_dir = output_dir.join("dags");
    std::fs::create_dir_all(&dags_dir).map_err(|e| ParseError::CodegenIo {
        path: dags_dir.display().to_string(),
        source: e,
    })?;

    let mut count = 0usize;

    for ir in irs {
        let Some(tpl_rel) = select_template(ir) else {
            tracing::debug!(
                job = %ir.job_id,
                pattern = %ir.pattern,
                "codegen: skipped (no template for this pattern/os/transfer_type)"
            );
            continue;
        };

        let tpl_path = templates_dir.join(tpl_rel);

        let Some(mut subs) = build_substitutions(ir, company, env) else {
            tracing::warn!(job = %ir.job_id, "codegen: skipped (missing required IR fields)");
            continue;
        };

        // Merge optional override config — config keys win over IR-derived defaults
        let config_path = config_dir
            .join(env)
            .join(format!("{}.json", ir.job_id));
        let config_used = merge_config_overrides(&mut subs, &config_path, &ir.job_id);

        let rendered = match render_template(&tpl_path, &subs) {
            Ok(r) => r,
            Err(ParseError::TemplateNotFound(ref p)) => {
                tracing::warn!(job = %ir.job_id, path = %p, "codegen: template file not found — skipped");
                continue;
            }
            Err(e) => return Err(e),
        };

        let dag_id = build_dag_id(&subs);
        let dag_filename = format!("{}.py", dag_id);
        let out_path = dags_dir.join(&dag_filename);

        // Prepend generation header
        let config_line = if config_used {
            format!("# Config    : config/{}/{}.json (overrides applied)\n", env, ir.job_id)
        } else {
            format!("# Config    : (none — all values derived from IR)\n")
        };
        let header = format!(
            "# Generated by ctm-parser codegen\n\
             # Template : {}\n\
             # Source IR: {} / {}\n\
             # Company  : {}  Env: {}\n\
             {}\n",
            tpl_rel,
            ir.source_folder,
            ir.job_id,
            company,
            env,
            config_line,
        );
        let final_content = format!("{}{}", header, rendered);

        std::fs::write(&out_path, &final_content).map_err(|e| ParseError::CodegenIo {
            path: out_path.display().to_string(),
            source: e,
        })?;

        // Write codegen metadata back into the IR JSON file on disk
        let meta = CodegenMeta {
            template: tpl_rel.to_string(),
            dag_file: dag_filename.clone(),
            company: company.to_string(),
            env: env.to_string(),
            config_override: config_used.then(|| config_path.display().to_string()),
        };
        write_codegen_meta(ir, &meta, output_dir);

        tracing::debug!(
            job = %ir.job_id,
            dag_id = %dag_id,
            template = %tpl_rel,
            config_override = config_used,
            "codegen: DAG written"
        );
        count += 1;
    }

    Ok(count)
}

/// Dump IR-derived substitution defaults to a config JSON file for manual editing.
/// Engineers can then edit this file and place it in `config/<scenario>/<env>/` to override specific values.
pub fn dump_config(
    irs: &[JobIr],
    config_dir: &Path,
    company: &str,
    env: &str,
) -> Result<usize, ParseError> {
    let config_dir = config_dir.join(env);
    std::fs::create_dir_all(&config_dir).map_err(|e| ParseError::CodegenIo {
        path: config_dir.display().to_string(),
        source: e,
    })?;

    let mut count = 0usize;

    for ir in irs {
        if select_template(ir).is_none() {
            continue;
        }
        let Some(subs) = build_substitutions(ir, company, env) else {
            continue;
        };

        // Convert ##KEY## map → plain KEY map for the JSON file
        let plain: serde_json::Map<String, serde_json::Value> = subs
            .into_iter()
            .map(|(k, v)| {
                let key = k.trim_matches('#').to_string();
                (key, serde_json::Value::String(v))
            })
            .collect();

        let config_path = config_dir.join(format!("{}.json", ir.job_id));
        let json = serde_json::to_string_pretty(&serde_json::Value::Object(plain))?;
        std::fs::write(&config_path, json).map_err(|e| ParseError::CodegenIo {
            path: config_path.display().to_string(),
            source: e,
        })?;

        tracing::debug!(job = %ir.job_id, path = %config_path.display(), "codegen: config dumped");
        count += 1;
    }

    tracing::info!(configs_written = count, env = %env, "config files dumped");
    Ok(count)
}

/// Load a config JSON and merge its values (as ##KEY## overrides) into the substitution map.
/// Returns true if the config file was found and applied.
fn merge_config_overrides(
    subs: &mut HashMap<String, String>,
    config_path: &Path,
    job_id: &str,
) -> bool {
    if !config_path.exists() {
        return false;
    }

    let raw = match std::fs::read_to_string(config_path) {
        Ok(s) => s,
        Err(e) => {
            tracing::warn!(job = %job_id, path = %config_path.display(), error = %e,
                "codegen: failed to read config override — using IR defaults");
            return false;
        }
    };

    let parsed: serde_json::Value = match serde_json::from_str(&raw) {
        Ok(v) => v,
        Err(e) => {
            tracing::warn!(job = %job_id, path = %config_path.display(), error = %e,
                "codegen: config JSON parse error — using IR defaults");
            return false;
        }
    };

    let obj = match parsed.as_object() {
        Some(o) => o,
        None => {
            tracing::warn!(job = %job_id, "codegen: config JSON is not an object — using IR defaults");
            return false;
        }
    };

    let mut overrides_applied = 0usize;
    for (key, val) in obj {
        let placeholder = format!("##{key}##");
        if let Some(v) = val.as_str() {
            subs.insert(placeholder, v.to_string());
            overrides_applied += 1;
        } else {
            // Booleans and arrays: serialize as Python literals
            let py_val = json_to_python_literal(val);
            subs.insert(placeholder, py_val);
            overrides_applied += 1;
        }
    }

    tracing::info!(
        job = %job_id,
        path = %config_path.display(),
        overrides = overrides_applied,
        "codegen: config overrides applied"
    );
    true
}

/// Convert a JSON value to a Python literal string for template substitution.
fn json_to_python_literal(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::Bool(b) => if *b { "True" } else { "False" }.into(),
        serde_json::Value::Array(arr) => {
            let items: Vec<String> = arr
                .iter()
                .map(|item| match item {
                    serde_json::Value::String(s) => format!("\"{}\"", s),
                    other => other.to_string(),
                })
                .collect();
            format!("[{}]", items.join(", "))
        }
        serde_json::Value::Null => "None".into(),
        other => other.to_string(),
    }
}

/// Returns the template relative path (from templates_dir) for this IR, or None to skip.
/// Only single-job (no upstream INCOND) FileTransfer onprem_to_onprem linux jobs are supported.
fn select_template(ir: &JobIr) -> Option<&'static str> {
    if ir.pattern != "FileTransfer" {
        return None;
    }
    // Skip jobs with upstream dependencies — template is single-DAG only (no ExternalTaskSensor)
    if !ir.dependencies.upstream.is_empty() {
        return None;
    }
    let dc = ir.dag_config.as_ref()?;
    if dc.agent_os != "linux" {
        return None;
    }
    let pc = dc.plugin_config.as_ref()?;
    let transfer_type = pc.get("transfer_type")?.as_str()?;
    if transfer_type != "onprem_to_onprem" {
        return None;
    }
    Some("file-transfer-onprem-onprem-unix/dags/project_file_transfer_onprem_onprem_unix.py")
}

/// Build the ##KEY## → value substitution map from a JobIr.
/// Returns None if any required field is missing.
fn build_substitutions(ir: &JobIr, company: &str, env: &str) -> Option<HashMap<String, String>> {
    let dc = ir.dag_config.as_ref()?;
    let pc = dc.plugin_config.as_ref()?;

    let application    = dc.application.as_deref().unwrap_or("").to_lowercase();
    let sub_application = dc.sub_application.as_deref().unwrap_or("").to_lowercase();
    let folder_lower   = ir.source_folder.to_lowercase();
    let env_lower      = env.to_lowercase();
    let nodeid         = dc.nodeid.to_lowercase();

    let transfers = pc.get("transfers")?.as_array()?;
    let tr = transfers.first()?;

    let direction  = tr.get("direction")?.as_str()?.to_lowercase();
    let local_path = tr.get("local_path").and_then(|v| v.as_str()).unwrap_or("");
    let remote_path = tr.get("remote_path").and_then(|v| v.as_str()).unwrap_or("");

    let (source_path, dest_path) = if direction.starts_with("download") {
        (remote_path, local_path)
    } else {
        (local_path, remote_path)
    };

    let protocol_raw = pc.get("protocol").and_then(|v| v.as_str()).unwrap_or("ftp");
    let protocol = normalize_protocol(protocol_raw);

    let dest_host  = pc.get("remote_host").and_then(|v| v.as_str()).unwrap_or("");
    let dest_user  = pc.get("account").and_then(|v| v.as_str()).unwrap_or("");
    let dest_port  = default_port(&protocol);

    let pre_command  = tr.get("pre_command").and_then(|v| v.as_str()).unwrap_or("");
    let post_command = tr.get("post_command").and_then(|v| v.as_str()).unwrap_or("");

    let schedule = dc.schedule.as_deref().unwrap_or("@daily");

    let tags_literal = format!(
        "[\"{}\", \"{}\", \"{}\", \"{}\", \"file-transfer\"]",
        application, sub_application, folder_lower, env_lower
    );

    let password_var = format!(
        "FTP_{}_PASS",
        dest_user.to_uppercase().replace('-', "_").replace(' ', "_")
    );

    let mut subs = HashMap::new();
    subs.insert("##COMPANY##".into(),   company.to_lowercase());
    subs.insert("##PROJECT##".into(),   application.clone());
    subs.insert("##APP_CODE##".into(),  sub_application.clone());
    subs.insert("##ENV##".into(),       env_lower.clone());
    subs.insert("##DAG_NAME##".into(),  folder_lower.clone());
    subs.insert("##ACTIVE##".into(),    "True".into());
    subs.insert("##SCHEDULE##".into(),  schedule.into());
    subs.insert("##TAGS##".into(),      tags_literal);
    subs.insert("##EMAIL_LIST##".into(),                         "[]".into());
    subs.insert("##ENABLE_EMAIL_NOTIFICATION_SUCCESS##".into(),  "False".into());
    subs.insert("##ENABLE_EMAIL_NOTIFICATION_FAIL##".into(),     "True".into());
    subs.insert("##SSH_CONN_ID##".into(),  format!("ssh_{}_{}", nodeid, env_lower));
    subs.insert("##REMOTE_HOST##".into(),  dc.nodeid.clone());
    subs.insert("##PROTOCOL##".into(),     protocol.clone());
    subs.insert("##DIRECTION##".into(),    direction);
    subs.insert("##SOURCE_PATH##".into(),  source_path.into());
    subs.insert("##DEST_HOST##".into(),    dest_host.into());
    subs.insert("##DEST_PORT##".into(),    dest_port.into());
    subs.insert("##DEST_USER##".into(),    dest_user.into());
    subs.insert("##DEST_PATH##".into(),    dest_path.into());
    subs.insert("##PASSWORD_VAR##".into(), password_var);
    subs.insert("##NEW_NAME##".into(),       "".into());
    subs.insert("##ARCHIVE_PATH##".into(),   "".into());
    subs.insert("##RETENTION_DAYS##".into(), "30".into());
    subs.insert("##PRE_COMMAND##".into(),    pre_command.into());
    subs.insert("##PRE_COMMAND_ARGS##".into(),  "".into());
    subs.insert("##POST_COMMAND##".into(),   post_command.into());
    subs.insert("##POST_COMMAND_ARGS##".into(), "".into());

    Some(subs)
}

/// Read template, apply all ##KEY## substitutions, return rendered string.
fn render_template(template_path: &Path, subs: &HashMap<String, String>) -> Result<String, ParseError> {
    if !template_path.exists() {
        return Err(ParseError::TemplateNotFound(template_path.display().to_string()));
    }
    let mut content = std::fs::read_to_string(template_path).map_err(|e| ParseError::CodegenIo {
        path: template_path.display().to_string(),
        source: e,
    })?;
    for (placeholder, value) in subs {
        content = content.replace(placeholder.as_str(), value.as_str());
    }
    Ok(content)
}

/// Build DAG ID from the merged substitution map so config overrides affect the filename.
fn build_dag_id(subs: &HashMap<String, String>) -> String {
    let get = |key: &str| {
        subs.get(key).map(|s| s.to_lowercase().replace(' ', "_")).unwrap_or_default()
    };
    format!(
        "{}-{}-{}-{}-{}",
        get("##COMPANY##"),
        get("##PROJECT##"),
        get("##APP_CODE##"),
        get("##DAG_NAME##"),
        get("##ENV##"),
    )
}

/// Patch the IR JSON file on disk to add the `codegen` field.
/// Reads, merges, rewrites — best-effort (logs warning on any error, never fails the build).
fn write_codegen_meta(ir: &JobIr, meta: &CodegenMeta, output_dir: &Path) {
    let stem = {
        let folder = ir.source_folder.replace(['/', '\\', ':'], "_");
        let job = ir.job_id.replace(['/', '\\', ':'], "_");
        format!("job__{}__{}", folder, job)
    };
    let ir_path = output_dir
        .join("ir")
        .join(format!("{}.json", stem));

    let patch = || -> Result<(), Box<dyn std::error::Error>> {
        let raw = std::fs::read_to_string(&ir_path)?;
        let mut v: serde_json::Value = serde_json::from_str(&raw)?;
        v["codegen"] = serde_json::json!({
            "template": meta.template,
            "dag_file": meta.dag_file,
            "company":  meta.company,
            "env":      meta.env,
        });
        std::fs::write(&ir_path, serde_json::to_string_pretty(&v)?)?;
        Ok(())
    };

    if let Err(e) = patch() {
        tracing::warn!(job = %ir.job_id, error = %e, "codegen: failed to patch IR JSON with codegen meta");
    }
}

fn normalize_protocol(raw: &str) -> String {
    match raw.to_ascii_lowercase().as_str() {
        "ftp-ssl" | "ftps" => "ftps".into(),
        "sftp"             => "sftp".into(),
        _                  => "ftp".into(),
    }
}

fn default_port(protocol: &str) -> &'static str {
    match protocol {
        "sftp" => "22",
        _      => "21",
    }
}
